from .add import AddCommand
from .backup import BackupCommand
from .configure import ConfigureCommand
from .copy import CopyCommand
from .create import CreateCommand
from .delete import DeleteCommand
from .modify import ModifyCommand
from .rename import RenameCommand
from .transfer import TransferCommand
from .exec import ExecCommand
